- targets:  # url;humanname;routing;switch
    - http://www.google.com/;google.com;external;internetbox
    # - https://github.com/;github.com;external;internetbox
    # - https://www.jeffgeerling.com;jeffgeerling.com;external;internetbox
    # - http://192.168.1.1;internetbox;local;internetbox
    # - http://192.168.1.42;blackdata;local;orbirouter-attic
    # - http://192.168.1.101;orbirouter;local;orbirouter
    - 1.1.1.1;1.1.1.1;external;internetbox
    - 192.168.1.1;192.168.1.1;external;internetbox
    - jc.jrcreativetech.ca;jc.jrcreativetech.ca;external;internetbox
    - js.jrcreativetech.ca;js.jrcreativetech.ca;external;internetbox
    - jr.jrcreativetech.ca;jr.jrcreativetech.ca;external;internetbox
    - https://www.jrcreativetech.ca/;jrcreativetech.ca;external;internetbox
    - https://ucrm.jrcreativetech.ca/;ucrm.jrcreativetech.ca;external;internetbox